### ISSUE TITLE
Deploy with Github Pages

### ISSUE THREAD

**Issue by digitaltopo** [Aria-experience/aria#4]
Deploy the live website and host on Github Pages.

## Tasks

- [ ] Setup deployment
- [ ] Setup custom domain name
- [ ] Document deployment process in runbook
- [ ] Create wiki article with deployment resources
- [ ] *Bonus:* Setup automated deployments / [CI](https://en.wikipedia.org/wiki/Continuous_integration) (Triggered by push/merge to master branch)

## Resources
* [Github Pages](https://pages.github.com/)
* [https://github.com/tschaub/gh-pages](gh-pages) - NPM package that helps deploy to gh-pages

### Guides / Tutorials
* [So you want to host your Single Page React App on GitHub Pages?](https://itnext.io/so-you-want-to-host-your-single-age-react-app-on-github-pages-a826ab01e48)
* [Deploy React to GitHub-Pages to create an amazing website!](https://codeburst.io/deploy-react-to-github-pages-to-create-an-amazing-website-42d8b09cd4d)
